import type { Module } from '@/types'

const module: Module = {
  slug: 'buying-clothes',
  titleEn: 'Buying Clothes',
  titleEs: 'Comprar Ropa',
  descriptionEn: 'Learn how to shop for clothes and ask for help at a store.',
  descriptionEs: 'Aprende a comprar ropa y pedir ayuda en una tienda.',
  icon: 'Shirt',
  vocab: [
    {
      id: 'size',
      en: 'size',
      es: 'la talla / el tamaño',
      pronunciation: 'SYZ',
      exampleEn: 'What size do you wear?',
      exampleEs: '¿Qué talla usas?',
    },
    {
      id: 'fitting-room',
      en: 'fitting room',
      es: 'el probador',
      pronunciation: 'FIH-ting room',
      exampleEn: 'Can I use the fitting room to try this on?',
      exampleEs: '¿Puedo usar el probador para probarme esto?',
    },
    {
      id: 'too-big-small',
      en: 'too big / too small',
      es: 'muy grande / muy pequeño',
      pronunciation: 'too BIG / too SMAWL',
      exampleEn: 'This shirt is too big. Do you have a smaller size?',
      exampleEs: 'Esta camisa es muy grande. ¿Tiene una talla más pequeña?',
    },
    {
      id: 'do-you-have',
      en: 'Do you have this in...?',
      es: '¿Tiene esto en...?',
      pronunciation: 'doo yoo HAV this in',
      exampleEn: 'Do you have this in blue? Do you have this in a size medium?',
      exampleEs: '¿Tiene esto en azul? ¿Tiene esto en talla mediana?',
    },
    {
      id: 'return',
      en: 'return / exchange',
      es: 'devolver / cambiar',
      pronunciation: 'reh-TURN / eks-CHAYNJ',
      exampleEn: 'I would like to return this shirt, please.',
      exampleEs: 'Me gustaría devolver esta camisa, por favor.',
    },
    {
      id: 'discount',
      en: 'discount',
      es: 'el descuento',
      pronunciation: 'DIS-kownt',
      exampleEn: 'Is there a discount on these shoes?',
      exampleEs: '¿Hay algún descuento en estos zapatos?',
    },
    {
      id: 'try-on',
      en: 'try on',
      es: 'probarse',
      pronunciation: 'try ON',
      exampleEn: 'Can I try on this jacket?',
      exampleEs: '¿Me puedo probar esta chaqueta?',
    },
    {
      id: 'i-am-looking-for',
      en: 'I am looking for...',
      es: 'Estoy buscando...',
      pronunciation: 'eye AM LOOK-ing for',
      exampleEn: 'I am looking for a warm coat for winter.',
      exampleEs: 'Estoy buscando un abrigo caliente para el invierno.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'Where do you try on clothes in a store?',
      promptEs: '¿Dónde te pruebas la ropa en una tienda?',
      answer: 'Fitting room',
      options: ['Fitting room', 'Cashier', 'Aisle', 'Exit'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'How do you say "Esta camisa es muy grande" in English?',
      promptEs: '¿Cómo se dice "Esta camisa es muy grande" en inglés?',
      answer: 'This shirt is too big',
      options: ['This shirt is too big', 'This shirt is too small', 'This shirt is on sale', 'This shirt is my size'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Estoy buscando..." in English is:',
      promptEs: '"Estoy buscando..." en inglés es:',
      answer: 'I am looking for...',
      options: ['I am looking for...', 'I am trying on...', 'I want to return...', 'Do you have...?'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you ask if a store has something in a different color?',
      promptEs: '¿Cómo preguntas si una tienda tiene algo en otro color?',
      answer: 'Do you have this in...?',
      options: ['Do you have this in...?', 'Where is the fitting room?', 'Can I return this?', 'What is the size?'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"El descuento" in English is:',
      promptEs: '"El descuento" en inglés es:',
      answer: 'discount',
      options: ['discount', 'receipt', 'return', 'exchange'],
    },
  ],
  teachingScenario: 'You are at a clothing store in New York. You need to find a coat for winter but you do not know your size in American sizes, and you need help asking about the fitting room, prices, and whether items come in different colors.',
  homeworkUrl: 'https://www.duolingo.com/learn',
  homeworkLabel: 'Duolingo – Shopping & Clothing',
}

export default module
