import type { Module } from '@/types'

const module: Module = {
  slug: 'buying-groceries',
  titleEn: 'Buying Groceries',
  titleEs: 'Comprar Comida',
  descriptionEn: 'Learn how to shop for food at a supermarket in New York.',
  descriptionEs: 'Aprende a hacer compras en un supermercado en Nueva York.',
  icon: 'ShoppingCart',
  vocab: [
    {
      id: 'aisle',
      en: 'aisle',
      es: 'el pasillo',
      pronunciation: 'EYE-ul',
      exampleEn: 'The rice is in aisle 5.',
      exampleEs: 'El arroz está en el pasillo 5.',
    },
    {
      id: 'how-much',
      en: 'How much does this cost?',
      es: '¿Cuánto cuesta esto?',
      pronunciation: 'how MUCH duz THIS kawst',
      exampleEn: 'Excuse me, how much does this cost?',
      exampleEs: 'Disculpe, ¿cuánto cuesta esto?',
    },
    {
      id: 'receipt',
      en: 'receipt',
      es: 'el recibo',
      pronunciation: 'reh-SEET',
      exampleEn: 'Can I have a receipt, please?',
      exampleEs: '¿Me puede dar el recibo, por favor?',
    },
    {
      id: 'cashier',
      en: 'cashier',
      es: 'el cajero / la cajera',
      pronunciation: 'kah-SHEER',
      exampleEn: 'Pay at the cashier at the front of the store.',
      exampleEs: 'Paga en la caja al frente de la tienda.',
    },
    {
      id: 'bag',
      en: 'bag',
      es: 'la bolsa',
      pronunciation: 'BAG',
      exampleEn: 'Do you need a bag for your groceries?',
      exampleEs: '¿Necesita una bolsa para sus compras?',
    },
    {
      id: 'on-sale',
      en: 'on sale',
      es: 'en oferta / en descuento',
      pronunciation: 'on SAYL',
      exampleEn: 'The chicken is on sale this week.',
      exampleEs: 'El pollo está en oferta esta semana.',
    },
    {
      id: 'where-is',
      en: 'Where is the...?',
      es: '¿Dónde está el/la...?',
      pronunciation: 'wer IZ thuh',
      exampleEn: 'Excuse me, where is the milk?',
      exampleEs: 'Disculpe, ¿dónde está la leche?',
    },
    {
      id: 'cash-credit',
      en: 'cash or credit card',
      es: 'efectivo o tarjeta de crédito',
      pronunciation: 'KASH or KREH-dit kard',
      exampleEn: 'Will you be paying with cash or credit card?',
      exampleEs: '¿Va a pagar con efectivo o tarjeta de crédito?',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'How do you ask where something is in a store?',
      promptEs: '¿Cómo preguntas dónde está algo en una tienda?',
      answer: 'Where is the...?',
      options: ['Where is the...?', 'How much does this cost?', 'Can I have a receipt?', 'Is this on sale?'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: '"El pasillo" in English is:',
      promptEs: '"El pasillo" en inglés es:',
      answer: 'aisle',
      options: ['aisle', 'cashier', 'receipt', 'bag'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: 'How do you ask the price of something?',
      promptEs: '¿Cómo preguntas el precio de algo?',
      answer: 'How much does this cost?',
      options: ['How much does this cost?', 'Where is the cashier?', 'Can I have a bag?', 'Is this on sale?'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: '"En oferta" in English means:',
      promptEs: '"En oferta" en inglés significa:',
      answer: 'on sale',
      options: ['on sale', 'on aisle', 'on cash', 'on receipt'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: 'The person who takes your payment at the store is called:',
      promptEs: 'La persona que recibe tu pago en la tienda se llama:',
      answer: 'cashier',
      options: ['cashier', 'manager', 'customer', 'bagger'],
    },
  ],
  teachingScenario: 'You are at a supermarket in Queens. You need to buy rice, bread, and vegetables but do not know how to ask where things are, how much they cost, or how to pay.',
  homeworkUrl: 'https://www.usalearns.org/unit2',
  homeworkLabel: 'USA Learns Unit 2 – Shopping',
}

export default module
