import type { Module } from '@/types'

const module: Module = {
  slug: 'family-tree',
  titleEn: 'Family',
  titleEs: 'La Familia',
  descriptionEn: 'Learn how to talk about your family members in English.',
  descriptionEs: 'Aprende a hablar de los miembros de tu familia en inglés.',
  icon: 'Users',
  vocab: [
    {
      id: 'mother',
      en: 'mother / mom',
      es: 'la madre / mamá',
      pronunciation: 'MUH-ther / MOM',
      exampleEn: 'My mother is a great cook.',
      exampleEs: 'Mi mamá cocina muy bien.',
    },
    {
      id: 'father',
      en: 'father / dad',
      es: 'el padre / papá',
      pronunciation: 'FAH-ther / DAD',
      exampleEn: 'My father works in construction.',
      exampleEs: 'Mi papá trabaja en construcción.',
    },
    {
      id: 'brother',
      en: 'brother',
      es: 'el hermano',
      pronunciation: 'BRUH-ther',
      exampleEn: 'I have two brothers and one sister.',
      exampleEs: 'Tengo dos hermanos y una hermana.',
    },
    {
      id: 'sister',
      en: 'sister',
      es: 'la hermana',
      pronunciation: 'SIS-ter',
      exampleEn: 'My sister lives in the Bronx.',
      exampleEs: 'Mi hermana vive en el Bronx.',
    },
    {
      id: 'son',
      en: 'son',
      es: 'el hijo',
      pronunciation: 'SUN',
      exampleEn: 'My son is seven years old.',
      exampleEs: 'Mi hijo tiene siete años.',
    },
    {
      id: 'daughter',
      en: 'daughter',
      es: 'la hija',
      pronunciation: 'DAW-ter',
      exampleEn: 'My daughter is learning English at school.',
      exampleEs: 'Mi hija está aprendiendo inglés en la escuela.',
    },
    {
      id: 'grandparents',
      en: 'grandparents',
      es: 'los abuelos',
      pronunciation: 'GRAND-peh-rents',
      exampleEn: 'My grandparents stayed in Mexico.',
      exampleEs: 'Mis abuelos se quedaron en México.',
    },
    {
      id: 'i-have',
      en: 'I have... / I don\'t have...',
      es: 'Tengo... / No tengo...',
      pronunciation: 'eye HAV / eye DONT hav',
      exampleEn: 'I have three children. I don\'t have any brothers.',
      exampleEs: 'Tengo tres hijos. No tengo hermanos.',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: '"La hermana" in English is:',
      promptEs: '"La hermana" en inglés es:',
      answer: 'sister',
      options: ['sister', 'daughter', 'mother', 'aunt'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: '"My son is seven years old" means:',
      promptEs: '"My son is seven years old" significa:',
      answer: 'Mi hijo tiene siete años',
      options: ['Mi hijo tiene siete años', 'Mi hermano tiene siete años', 'Mi padre tiene siete años', 'Mi hijo tiene siete hijos'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Los abuelos" in English is:',
      promptEs: '"Los abuelos" en inglés es:',
      answer: 'grandparents',
      options: ['grandparents', 'parents', 'children', 'cousins'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you say "Tengo dos hijos" in English?',
      promptEs: '¿Cómo se dice "Tengo dos hijos" en inglés?',
      answer: 'I have two children',
      options: ['I have two children', 'I have two brothers', 'I don\'t have children', 'My two sons'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"La hija" in English is:',
      promptEs: '"La hija" en inglés es:',
      answer: 'daughter',
      options: ['daughter', 'sister', 'mother', 'grandmother'],
    },
  ],
  teachingScenario: 'You are talking with a new friend at the church. They want to know about your family, and you want to ask about their family too, but you do not know the English words for family members.',
  homeworkUrl: 'https://www.usalearns.org/unit3',
  homeworkLabel: 'USA Learns Unit 3 – Family',
}

export default module
