import type { Module } from '@/types'

const module: Module = {
  slug: 'introducing-yourself',
  titleEn: 'Introducing Yourself',
  titleEs: 'Presentarte',
  descriptionEn: 'Learn how to meet new people and share basic information about yourself.',
  descriptionEs: 'Aprende a conocer personas nuevas y compartir información básica sobre ti.',
  icon: 'Hand',
  vocab: [
    {
      id: 'my-name-is',
      en: 'My name is...',
      es: 'Me llamo... / Mi nombre es...',
      pronunciation: 'my NAYM iz',
      exampleEn: 'My name is Maria. Nice to meet you!',
      exampleEs: 'Me llamo María. ¡Mucho gusto!',
    },
    {
      id: 'nice-to-meet-you',
      en: 'Nice to meet you',
      es: 'Mucho gusto',
      pronunciation: 'nys to MEET yoo',
      exampleEn: 'Nice to meet you! My name is Carlos.',
      exampleEs: '¡Mucho gusto! Me llamo Carlos.',
    },
    {
      id: 'i-am-from',
      en: 'I am from...',
      es: 'Soy de...',
      pronunciation: 'eye AM frum',
      exampleEn: 'I am from Mexico. Where are you from?',
      exampleEs: 'Soy de México. ¿De dónde eres tú?',
    },
    {
      id: 'i-live-in',
      en: 'I live in...',
      es: 'Vivo en...',
      pronunciation: 'eye LIV in',
      exampleEn: 'I live in Queens, New York.',
      exampleEs: 'Vivo en Queens, Nueva York.',
    },
    {
      id: 'i-speak',
      en: 'I speak...',
      es: 'Hablo...',
      pronunciation: 'eye SPEEK',
      exampleEn: 'I speak Spanish and a little English.',
      exampleEs: 'Hablo español y un poco de inglés.',
    },
    {
      id: 'how-are-you',
      en: 'How are you?',
      es: '¿Cómo estás?',
      pronunciation: 'how AR yoo',
      exampleEn: 'Hello! How are you today?',
      exampleEs: '¡Hola! ¿Cómo estás hoy?',
    },
    {
      id: 'i-am-fine',
      en: 'I am fine, thank you',
      es: 'Estoy bien, gracias',
      pronunciation: 'eye AM fyn THANK yoo',
      exampleEn: 'I am fine, thank you. And you?',
      exampleEs: 'Estoy bien, gracias. ¿Y tú?',
    },
    {
      id: 'what-is-your-name',
      en: 'What is your name?',
      es: '¿Cómo te llamas?',
      pronunciation: 'wut IZ yor NAYM',
      exampleEn: 'Excuse me, what is your name?',
      exampleEs: 'Disculpa, ¿cómo te llamas?',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'How do you say "Me llamo..." in English?',
      promptEs: '¿Cómo se dice "Me llamo..." en inglés?',
      answer: 'My name is...',
      options: ['My name is...', 'I live in...', 'I am from...', 'How are you?'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'What does "Nice to meet you" mean?',
      promptEs: '¿Qué significa "Nice to meet you"?',
      answer: 'Mucho gusto',
      options: ['Mucho gusto', 'Hasta luego', 'Soy de México', 'Estoy bien'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: 'How do you ask someone\'s name in English?',
      promptEs: '¿Cómo preguntas el nombre de alguien en inglés?',
      answer: 'What is your name?',
      options: ['What is your name?', 'Where are you from?', 'How are you?', 'I live in...'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: '"Soy de México" in English is:',
      promptEs: '"Soy de México" en inglés es:',
      answer: 'I am from Mexico',
      options: ['I am from Mexico', 'I live in Mexico', 'I speak Mexico', 'I am Mexico'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: 'How do you respond when someone asks "How are you?"',
      promptEs: '¿Cómo respondes cuando alguien pregunta "How are you?"',
      answer: 'I am fine, thank you',
      options: ['I am fine, thank you', 'Nice to meet you', 'My name is Carlos', 'I am from Queens'],
    },
  ],
  teachingScenario: 'You just arrived at a church community event in Queens. You want to meet the people there but do not know how to introduce yourself or start a conversation in English.',
  homeworkUrl: 'https://www.usalearns.org/unit1',
  homeworkLabel: 'USA Learns Unit 1 – Meeting People',
}

export default module
