import type { Module } from '@/types'

const module: Module = {
  slug: 'navigating-subway',
  titleEn: 'Navigating the Subway',
  titleEs: 'El Metro',
  descriptionEn: 'Learn the words and phrases you need to ride the NYC subway with confidence.',
  descriptionEs: 'Aprende las palabras y frases para viajar en el metro de Nueva York con confianza.',
  icon: 'Train',
  vocab: [
    {
      id: 'subway',
      en: 'subway',
      es: 'el metro / el subterráneo',
      pronunciation: 'SUB-way',
      exampleEn: 'I take the subway to work every day.',
      exampleEs: 'Tomo el metro al trabajo todos los días.',
    },
    {
      id: 'metrocard',
      en: 'MetroCard',
      es: 'la tarjeta MetroCard',
      pronunciation: 'MEH-tro-kard',
      exampleEn: 'I need to buy a MetroCard at the machine.',
      exampleEs: 'Necesito comprar una MetroCard en la máquina.',
    },
    {
      id: 'platform',
      en: 'platform',
      es: 'el andén',
      pronunciation: 'PLAT-form',
      exampleEn: 'Wait for the train on the platform.',
      exampleEs: 'Espera el tren en el andén.',
    },
    {
      id: 'uptown',
      en: 'uptown',
      es: 'hacia el norte / uptown',
      pronunciation: 'UP-town',
      exampleEn: 'Take the uptown train to get to Manhattan.',
      exampleEs: 'Toma el tren uptown para ir a Manhattan.',
    },
    {
      id: 'downtown',
      en: 'downtown',
      es: 'hacia el sur / downtown',
      pronunciation: 'DOWN-town',
      exampleEn: 'The downtown train goes toward Brooklyn.',
      exampleEs: 'El tren downtown va hacia Brooklyn.',
    },
    {
      id: 'transfer',
      en: 'transfer',
      es: 'hacer transbordo / cambiar de tren',
      pronunciation: 'TRANS-fer',
      exampleEn: 'Transfer to the A train at Jay Street.',
      exampleEs: 'Haz transbordo al tren A en Jay Street.',
    },
    {
      id: 'exit',
      en: 'exit',
      es: 'la salida',
      pronunciation: 'EK-sit',
      exampleEn: 'Use the exit on the left side of the train.',
      exampleEs: 'Usa la salida del lado izquierdo del tren.',
    },
    {
      id: 'which-train',
      en: 'Which train goes to...?',
      es: '¿Qué tren va a...?',
      pronunciation: 'wich TRAYN goze too',
      exampleEn: 'Excuse me, which train goes to Times Square?',
      exampleEs: 'Disculpe, ¿qué tren va a Times Square?',
    },
  ],
  quiz: [
    {
      id: 'q1',
      type: 'multiple-choice',
      promptEn: 'What do you need to ride the subway in NYC?',
      promptEs: '¿Qué necesitas para viajar en el metro de Nueva York?',
      answer: 'MetroCard',
      options: ['MetroCard', 'Passport', 'Driver\'s license', 'Ticket'],
    },
    {
      id: 'q2',
      type: 'multiple-choice',
      promptEn: 'Where do you wait for the train?',
      promptEs: '¿Dónde esperas el tren?',
      answer: 'On the platform',
      options: ['On the platform', 'At the exit', 'In the street', 'At the machine'],
    },
    {
      id: 'q3',
      type: 'multiple-choice',
      promptEn: '"Uptown" means the train is going toward:',
      promptEs: '"Uptown" significa que el tren va hacia:',
      answer: 'Manhattan / north',
      options: ['Manhattan / north', 'Brooklyn / south', 'Queens / east', 'New Jersey / west'],
    },
    {
      id: 'q4',
      type: 'multiple-choice',
      promptEn: 'How do you ask which train to take?',
      promptEs: '¿Cómo preguntas qué tren tomar?',
      answer: 'Which train goes to...?',
      options: ['Which train goes to...?', 'Where is the exit?', 'How much is the MetroCard?', 'When is the next train?'],
    },
    {
      id: 'q5',
      type: 'multiple-choice',
      promptEn: '"Hacer transbordo" in English is:',
      promptEs: '"Hacer transbordo" en inglés es:',
      answer: 'to transfer',
      options: ['to transfer', 'to exit', 'to platform', 'to downtown'],
    },
  ],
  teachingScenario: 'You need to take the subway from Jackson Heights, Queens to Manhattan to get to a job interview, but you do not understand the subway signs, do not know which train to take, and are not sure how to buy a MetroCard.',
}

export default module
